-- CreateTable
CREATE TABLE "public"."system_settings" (
    "id" TEXT NOT NULL,
    "siteName" TEXT NOT NULL DEFAULT 'Norvis AI',
    "siteDescription" TEXT NOT NULL DEFAULT 'AI-powered chat application',
    "logoUrl" TEXT NOT NULL DEFAULT '/logo.png',
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMessage" TEXT,
    "allowRegistration" BOOLEAN NOT NULL DEFAULT true,
    "defaultModel" TEXT NOT NULL DEFAULT 'gpt-4-turbo',
    "maxTokensPerRequest" INTEGER NOT NULL DEFAULT 4000,
    "enableImageGeneration" BOOLEAN NOT NULL DEFAULT true,
    "enableCodeGeneration" BOOLEAN NOT NULL DEFAULT true,
    "enableVoiceChat" BOOLEAN NOT NULL DEFAULT false,
    "maxRequestsPerMinute" INTEGER NOT NULL DEFAULT 60,
    "sessionTimeout" INTEGER NOT NULL DEFAULT 24,
    "requireEmailVerification" BOOLEAN NOT NULL DEFAULT false,
    "enableTwoFactor" BOOLEAN NOT NULL DEFAULT false,
    "passwordMinLength" INTEGER NOT NULL DEFAULT 8,
    "smtpEnabled" BOOLEAN NOT NULL DEFAULT false,
    "smtpHost" TEXT DEFAULT 'smtp.gmail.com',
    "smtpPort" INTEGER DEFAULT 587,
    "smtpUser" TEXT,
    "smtpPassword" TEXT,
    "smtpFrom" TEXT DEFAULT 'noreply@norvis.ai',
    "smtpFromName" TEXT DEFAULT 'Norvis AI',
    "enableNotifications" BOOLEAN NOT NULL DEFAULT true,
    "notificationSound" BOOLEAN NOT NULL DEFAULT true,
    "enableEmailNotifications" BOOLEAN NOT NULL DEFAULT false,
    "enableAnalytics" BOOLEAN NOT NULL DEFAULT true,
    "enableErrorTracking" BOOLEAN NOT NULL DEFAULT true,
    "logLevel" TEXT NOT NULL DEFAULT 'info',
    "enableRateLimiting" BOOLEAN NOT NULL DEFAULT true,
    "enableCaching" BOOLEAN NOT NULL DEFAULT true,
    "cacheTimeout" INTEGER NOT NULL DEFAULT 3600,
    "updatedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "system_settings_pkey" PRIMARY KEY ("id")
);
